[package]
name = "haruhi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
femtovg = "0.7"
smallvec = "1.10"
thiserror = "1.0"
log = "0.4"
